spring:
  application:
    name: mafia
  profiles:
    active: local
    group:
      local: local, secret
      blue: blue, secret, prod
      green: green, secret, prod

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    redis:
      repositories:
        enabled: true

---
spring:
  config:
    activate:
      on-profile: blue
deploy:
  env: blue
server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: green
deploy:
  env: green
server:
  port: 8082