spring:
  application:
    name: mafia
  profiles:
    active: local
    group:
      local: local, secret
      blue: blue, secret, prod
      green: green, secret, prod



  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    redis:
      repositories:
        enabled: true

notification:
  mattermost:
    mmEnabled: true
    channel: "#alerts"
    pretext: "🚨 서버 에러 발생!"
    color: "#ff5d52"
    authorName: "Mafia Server"
    title: "백엔드 에러 로그"
    text: ""

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

application:
  version: 1.0.0

---
spring:
  config:
    activate:
      on-profile: blue
deploy:
  env: blue
server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: green
deploy:
  env: green
server:
  port: 8082